# Generated by Django 2.1.2 on 2019-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tender_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic_cats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_code', models.CharField(max_length=10)),
                ('cat_description', models.CharField(blank=True, max_length=450, null=True)),
                ('cat_kw', models.ManyToManyField(blank=True, to='tender_details.Keywords')),
            ],
        ),
    ]
