# Generated by Django 2.2 on 2019-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourdetails',
            name='website',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
