# Generated by Django 2.2 on 2019-07-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_auto_20190519_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='kw_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
