# Generated by Django 2.2.3 on 2019-07-31 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packages_package_id'),
        ('user_accounts', '0004_companyprofile_kw_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='invoiceItems',
        ),
        migrations.AddField(
            model_name='invoices',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Packages'),
        ),
    ]
