# Generated by Django 2.2.3 on 2019-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_auto_20190731_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_items',
            name='pymnt_status',
            field=models.BooleanField(default=False),
        ),
    ]
