# Generated by Django 2.2.3 on 2019-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_invoice_items_pymnt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_items',
            name='pymnt_status',
        ),
        migrations.AddField(
            model_name='invoices',
            name='pymnt_status',
            field=models.BooleanField(default=False),
        ),
    ]
