# Generated by Django 2.1.2 on 2019-04-06 12:27

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catDescription', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyersName', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField()),
                ('refNum', models.CharField(max_length=100)),
                ('issueDate', models.DateTimeField(blank=True, null=True)),
                ('closingDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('siteInspectionDate', models.DateTimeField(blank=True, null=True)),
                ('siteInspection', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('enquiries', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('matched', models.BooleanField(default=False)),
                ('capture_date', models.DateField(default=django.utils.timezone.now)),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('kw_assigned', models.BooleanField(blank=True, default=False)),
                ('tDocLinks', ckeditor.fields.RichTextField(blank=True)),
                ('assigned_keywords', models.ManyToManyField(blank=True, to='tender_details.Keywords')),
                ('tenderCategory', models.ManyToManyField(to='tender_details.Category')),
                ('tenderProvince', models.ManyToManyField(to='tender_details.Province')),
            ],
            options={
                'ordering': ['-closingDate'],
            },
        ),
    ]
