# Generated by Django 2.2 on 2019-06-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='pdfType',
            field=models.BooleanField(default=False),
        ),
    ]
