# Generated by Django 2.2 on 2019-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0002_tender_pdftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='pdfLink',
            field=models.TextField(blank=True),
        ),
    ]
