# Generated by Django 2.2.3 on 2021-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0003_tender_pdflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='topCat',
            field=models.BooleanField(default=False),
        ),
    ]
