# Generated by Django 2.2.3 on 2021-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0004_category_topcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='topCat_id',
            field=models.IntegerField(default=0),
        ),
    ]
