# Generated by Django 2.1.2 on 2019-04-10 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('articleBody', ckeditor.fields.RichTextField()),
                ('publisher', ckeditor.fields.RichTextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
